# -*- coding: utf-8 -*-
"""LeetCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vrwInB7gh08Bfiz2yMls1h8a4TvnLqGM
"""

class Solution(object):
    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        for i in range(len(nums)):
          for j in range(i+1, len(nums)):
            if (nums[i] + nums[j]) == target:
              return [i, j]

sol = Solution()
nums = [2,7,11,15]
target = 9
answer = sol.twoSum(nums, target)
print(answer)